import { MetadataRoute } from 'next';
import { baseUrl } from '@/lib/seo';
import { solutions, markets, technologies, industries, serviceRegionPaths } from '@/lib/data';
import { registrationStates } from '@/lib/company-registration';
import { routeLastModified } from '@/lib/sitemap-dates';

/**
 * Sitemap policy:
 * - Include only canonical, indexable content routes.
 * - `lastModified` is NOT written here. It comes from `lib/sitemap-dates.ts`,
 *   which is generated by `scripts/generate-sitemap-dates.mjs` from the last
 *   commit that changed each route's rendered body. Before 2026-09-08 the date
 *   was a literal on every entry defaulting to a `LAST_AUDIT` constant, and six
 *   content passes later most of the site was still declaring 2026-08-14 — the
 *   opposite of the truth, on exactly the pages that had just been rewritten.
 *   Re-run the script at the end of a content pass; do not hand-edit dates, and
 *   do not touch a page just to refresh one.
 * - Priority is retained only for framework compatibility; it is not
 *   used as a ranking strategy.
 * - Two live routes are deliberately absent, and the drift check in CLAUDE.md
 *   expects exactly those two: `/thank-you` and `/technology/myob`. Both are
 *   `noindex`, and a noindex URL in a sitemap is a contradiction Search Console
 *   reports.
 */

type Entry = { path: string; priority: number; changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency'] };

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes: Entry[] = [
    { path: '', priority: 1.0, changeFrequency: 'weekly' },
    { path: '/about', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/contact', priority: 0.8, changeFrequency: 'monthly' },
    { path: '/services', priority: 0.9, changeFrequency: 'weekly' },
    { path: '/solutions', priority: 0.9, changeFrequency: 'weekly' },
    { path: '/technology', priority: 0.8, changeFrequency: 'monthly' },
    { path: '/markets', priority: 0.8, changeFrequency: 'monthly' },
    { path: '/industries', priority: 0.8, changeFrequency: 'monthly' },
    { path: '/resources', priority: 0.7, changeFrequency: 'weekly' },
    { path: '/resources/case-studies', priority: 0.6, changeFrequency: 'monthly' },
    { path: '/resources/guides', priority: 0.7, changeFrequency: 'weekly' },
    { path: '/resources/insights', priority: 0.7, changeFrequency: 'weekly' },
    { path: '/delivery-framework/onboarding', priority: 0.5, changeFrequency: 'monthly' },
    { path: '/delivery-framework/communication', priority: 0.5, changeFrequency: 'monthly' },
    { path: '/delivery-framework/quality-assurance', priority: 0.5, changeFrequency: 'monthly' },
    { path: '/data-security', priority: 0.5, changeFrequency: 'monthly' },
    { path: '/compliance', priority: 0.5, changeFrequency: 'monthly' },
    { path: '/privacy', priority: 0.3, changeFrequency: 'yearly' },
    { path: '/cookie-policy', priority: 0.3, changeFrequency: 'yearly' },
    { path: '/terms', priority: 0.3, changeFrequency: 'yearly' },
  ];

  const dynamicRoutes: Entry[] = [
    // The 7 generic /services/{slug} URLs are deliberately NOT generated here.
    // They are 301s as of 2026-08-27 (see next.config.mjs) and a redirected URL
    // must not be declared in the sitemap. This is the drift trap CLAUDE.md
    // documents: these URLs came from a services.map() loop, so removing them
    // required changing the loop, not deleting lines. The 21 regional children
    // come from serviceRegionPaths and are the only /services/* URLs listed —
    // an earlier version also spelled all 21 out a second time by hand, which
    // was dead weight the dedupe silently swallowed.
    ...serviceRegionPaths.map((path) => ({ path, priority: 0.9, changeFrequency: 'monthly' as const })),
    ...solutions.map((s) => ({ path: `/solutions/${s.slug}`, priority: 0.85, changeFrequency: 'monthly' as const })),
    ...markets.map((m) => ({ path: `/markets/${m.slug}`, priority: 0.8, changeFrequency: 'monthly' as const })),
    // MYOB is noindex as of 2026-09-04 (see app/technology/myob/page.tsx).
    ...technologies
      .filter((t) => t.slug !== 'myob')
      .map((t) => ({ path: `/technology/${t.slug}`, priority: 0.75, changeFrequency: 'monthly' as const })),
    ...industries.map((i) => ({ path: `/industries/${i.slug}`, priority: 0.75, changeFrequency: 'monthly' as const })),
    { path: '/company-registration', priority: 0.7, changeFrequency: 'monthly' },
    ...registrationStates.map((st) => ({
      path: `/company-registration/${st.slug}`,
      priority: 0.6,
      changeFrequency: 'monthly' as const,
    })),
  ];

  const specializedRoutes: Entry[] = [
    { path: '/industries/real-estate/yardi-accounting-outsourcing-texas', priority: 0.6, changeFrequency: 'monthly' },
    { path: '/markets/united-states/texas', priority: 0.65, changeFrequency: 'monthly' },
    { path: '/markets/united-states/california', priority: 0.65, changeFrequency: 'monthly' },
    { path: '/markets/united-states/florida', priority: 0.65, changeFrequency: 'monthly' },
    // Guides. Four of these shipped 2026-08-14 but were unlisted for a week —
    // internally linked yet never declared for crawling. The accounting-services
    // guide matters most: it is the 301 target for the retired
    // /blog/outsourced-accounting-services URL.
    { path: '/resources/guides/outsourced-bookkeeping-cost-guide', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/resources/guides/quickbooks-vs-xero-comparison', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/resources/guides/staff-augmentation-tax-season-guide', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/resources/guides/questions-to-ask-before-outsourcing-bookkeeping', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/resources/guides/how-to-choose-accounting-outsourcing-partner', priority: 0.75, changeFrequency: 'monthly' },
    { path: '/resources/guides/client-accounting-services-cas-guide', priority: 0.75, changeFrequency: 'monthly' },
    { path: '/resources/guides/choosing-an-engagement-model', priority: 0.75, changeFrequency: 'monthly' },
    { path: '/resources/guides/outsourced-accounting-services-guide', priority: 0.75, changeFrequency: 'monthly' },
    { path: '/resources/guides/outsourced-payroll-processing-guide', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/resources/guides/outsourced-accounts-payable-guide', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/resources/guides/outsourced-accounts-receivable-guide', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/resources/insights/sales-tax-nexus-ecommerce-guide', priority: 0.6, changeFrequency: 'monthly' },
    { path: '/resources/insights/asc-606-revenue-recognition-saas', priority: 0.6, changeFrequency: 'monthly' },
    { path: '/blog', priority: 0.8, changeFrequency: 'weekly' },
    { path: '/blog/outsourced-bookkeeping-guide', priority: 0.75, changeFrequency: 'monthly' },
    { path: '/blog/accounts-payable-outsourcing', priority: 0.75, changeFrequency: 'monthly' },
    { path: '/blog/accounts-receivable-management', priority: 0.75, changeFrequency: 'monthly' },
    { path: '/blog/outsourced-payroll-services', priority: 0.75, changeFrequency: 'monthly' },
    { path: '/blog/tax-preparation-outsourcing', priority: 0.75, changeFrequency: 'monthly' },
    { path: '/blog/audit-support-services', priority: 0.75, changeFrequency: 'monthly' },
  ];

  const seen = new Set<string>();
  const allRoutes = [...staticRoutes, ...dynamicRoutes, ...specializedRoutes].filter((route) => {
    if (seen.has(route.path)) return false;
    seen.add(route.path);
    return true;
  });

  return allRoutes.map((route) => {
    const lastModified = routeLastModified[route.path];
    return {
      url: `${baseUrl}${route.path}`,
      changeFrequency: route.changeFrequency,
      priority: route.priority,
      ...(lastModified ? { lastModified } : {}),
    };
  });
}
